--- 
name: build
on: [push, pull_request]
jobs:
  std_tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
...
